apiVersion: v1
kind: Secret
metadata:
  name: secrets
data:
  POSTGRES_USER: cG9zdGdyZXMK  #echo -postgres | base64
  POSTGRES_PASSWORD: MTIzMQo=   #echo 1231 | base64
  AI21_TOKEN: bUo0U2ZaVkd1M1luMU10UXFwYk50MU5wemh2YmJFNmkK #echo mJ4SfZVGu3Yn1MtQqpbNt1NpzhvbbE6i | base64  
  REACT_APP_GOOGLE_KEY: QUl6YVN5QUFMMUd0R1hwTjNORWdjYlJVcVF2RXpOYVJNazc0MHVNCg== #echo AIzaSyAAL1GtGXpN3NEgcbRUqQvEzNaRMk740uM | base64
---

apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: 
type: kubernetes.io/dockerconfigjson