name: CD Workflow - develop-branch

on:
    pull_request:
      branches:
        - develop
      types: [closed]

jobs:
    build_and_push_to_registry:
        runs-on: self-hosted
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.merged == true }}
        steps:
            - uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build frontend image
              run: |
                cd frontend
                sudo docker build -t dev-frontend .
            - name: Build backend image
              run: |
                cd backend
                sudo docker build -t dev-backend .
            - name: Print images
              run: sudo docker images
            - name: Push production frontend image to registry
              run: |
                sudo docker tag dev-frontend:latest jubuitrago/tunefy:dev-frontend-$((${{ vars.DEV_VERSION }} + 1))
                sudo docker images
                sudo docker push jubuitrago/tunefy:dev-frontend-$((${{ vars.DEV_VERSION }} + 1))
            - name: Push production backend image to registry
              run: sudo docker push jubuitrago/tunefy:dev-backend-$((${{ vars.DEV_VERSION }} + 1))
            - name: Update dev-version on github
              uses: action-pack/set-variable@v1
              with:
                name: 'DEV_VERSION'
                value: $((${{ vars.DEV_VERSION }} + 1))
                token: ${{ secrets.REPO_ACCESS_TOKEN }}

    deploy:
        runs-on: self-hosted
        needs: build_and_push_to_registry
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.merged == true }}
        steps:
            - name: Deploy images to development environment
              run: |
                echo "deployment started"
    
    delete-feature-branch:
        runs-on: self-hosted
        needs: deploy
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.merged == true }}
        steps:
            - name: delete feature branch
              run: |
                echo "deleting feature branch"
            - name: Clean docker
              run: |
                if [ "$(sudo docker ps -q)" ]; then
                  sudo docker stop $(sudo docker ps -q)
                fi
                sudo docker system prune -af

