name: CD Workflow - develop-branch

on:
    pull_request:
      branches:
        - develop
      types: [closed]

jobs:
    build:
        runs-on: self-hosted
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.merged == true }}
        steps:
            - uses: actions/checkout@v3
            - name: Build frontend image
              run: |
                cd frontend
                echo "nueva version: "
                sudo docker build -t jubuitrago/tunefy:${{vars.DEV_VERSION}} .
            - name: Build backend image
              run: |
                cd backend
                sudo docker build -t jubuitrago/tunefy:${{vars.DEV_VERSION}} .
            - name: Set dev new version
              run: |

    push-to-registry:
        runs-on: self-hosted
        needs: build
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.merged == true }}
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Push production frontend image to registry
              run: |
                docker tag jubuitrago/tunefy:dev-frontend- jubuitrago/tunefy:prod-frontend-
                docker push jubuitrago/tunefy:prod-frontend-
            - name: Push production backend image to registry
              run: |
                docker tag jubuitrago/tunefy:dev-backend- jubuitrago/tunefy:prod-backend-
                docker push jubuitrago/tunefy:prod-backend-

    deploy:
        runs-on: self-hosted
        needs: push-to-registry
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.merged == true }}
        steps:
            - name: Deploy images to development environment
              run: |
                echo "deployment started"
    
    delete-feature-branch:
        runs-on: self-hosted
        needs: deploy
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.merged == true }}
        steps:
            - name: delete feature branch
              run: |
                echo "deleting feature branch"

