name: CD Workflow - develop-branch

on:
    pull_request:
      branches:
        - develop
      types: [closed]

jobs:
    build:
        runs-on: [self-hosted, dev-runner]
        if:  ${{ (github.base_ref == 'develop' && startsWith(github.ref, 'refs/heads/feature/') && github.event.pull_request.merged == true) }}
        steps:
            - uses: actions/checkout@v3
            - name: Build frontend image
              run: |
                cd frontend
                docker build -t frontend .
            - name: Build backend image
              run: |
                cd backend
                docker build -t backend .

    push-to-registry:
        runs-on: [self-hosted, dev-runner]
        needs: build
        if:  ${{ (github.base_ref == 'develop' && startsWith(github.ref, 'refs/heads/feature/') && github.event.pull_request.merged == true) }}
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Push production frontend image to registry
              run: |
                docker tag jubuitrago/tunefy:dev-frontend- jubuitrago/tunefy:prod-frontend-
                docker push jubuitrago/tunefy:prod-frontend-
            - name: Push production backend image to registry
              run: |
                docker tag jubuitrago/tunefy:dev-backend- jubuitrago/tunefy:prod-backend-
                docker push jubuitrago/tunefy:prod-backend-

    deploy:
        runs-on: [self-hosted, dev-runner]
        needs: push-to-registry
        if:  ${{ (github.base_ref == 'develop' && startsWith(github.ref, 'refs/heads/feature/') && github.event.pull_request.merged == true) }}
        steps:
            - name: Deploy images to development environment
              run: |
                echo "deployment started"
    
    delete-feature-branch:
        runs-on: [self-hosted, dev-runner]
        needs: deploy
        if:  ${{ (github.base_ref == 'develop' && startsWith(github.ref, 'refs/heads/feature/') && github.event.pull_request.merged == true) }}
        steps:
            - name: delete feature branch
              run: |
                echo "deleting feature branch"

