name: CD Workflow - main-branch - hotfix
#
on:
    pull_request:
      branches:
        - main
      types: [closed]

jobs:
    build_and_push_to_registry:
        runs-on: self-hosted
        if:  ${{ github.event.pull_request.merged == true && github.head_ref == 'hotfix' }}
        steps:
            - uses: actions/checkout@v3
            - name: Build frontend image
              run: |
                cd frontend
                docker build -t prod-frontend .
            - name: Build backend image
              run: |
                cd backend
                docker build -t prod-backend .
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set version
              id: set_version
              run: |
                CURRENT_VERSION=${{ vars.PROD_VERSION }}
                echo 'paso1'
                IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
                echo 'paso2'
                temp="${version_parts[2]}"
                echo 'paso3'
                temp=$((temp + 1))
                echo 'paso4'
                version_parts[2]=$temp
                echo 'paso5'
                NEW_VERSION="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
                echo 'paso6'
                echo "::set-output name=PROD_VERSION::$NEW_VERSION"

            - name: Push production frontend image to registry
              run: |
                docker tag prod-frontend:latest jubuitrago/tunefy:${{ steps.set_version.outputs.PROD_VERSION }}
                docker images
                docker push jubuitrago/tunefy:${{ steps.set_version.outputs.PROD_VERSION }}
            - name: Push production backend image to registry
              run: |
                docker tag prod-backend:latest jubuitrago/tunefy:${{ steps.set_version.outputs.PROD_VERSION }}
                docker images
                docker push jubuitrago/tunefy:${{ steps.set_version.outputs.PROD_VERSION }}
          
            - name: Update dev-version on github
              uses: action-pack/set-variable@v1
              with:
                name: 'PROD_VERSION'
                value: ${{ steps.set_version.outputs.PROD_VERSION }}
                token: ${{ secrets.REPO_ACCESS_TOKEN }}

    deploy:
        runs-on: self-hosted
        needs: build_and_push_to_registry
        if:  ${{ github.event.pull_request.merged == true && github.head_ref == 'hotfix' }}
        steps:
          - name: Deploy images to development environment
            run: |
              echo "deployment started"
              
    delete-feature-branch:
        runs-on: self-hosted
        needs: deploy
        if:  ${{ github.event.pull_request.merged == true && github.head_ref == 'hotfix' }}
        steps:
            - name: delete feature branch
              run: |
                echo "deleting feature branch"
            - name: Clean docker
              run: |
                if [ "$(docker ps -q)" ]; then
                  docker stop $(docker ps -q)
                fi
                docker system prune -af
