name: CD Workflow - main-branch - release

on:
    pull_request:
      branches:
        - main
      types: [closed]

jobs:
    build:
        runs-on: [self-hosted, prod-runner]
        if:  ${{ (github.base_ref == 'main' && github.event.pull_request.merged == true && github.head_ref == 'release') }}
        steps:
            - uses: actions/checkout@v3
            - name: Build frontend image
              run: |
                cd frontend
                docker build -t frontend .
            - name: Build backend image
              run: |
                cd backend
                docker build -t backend .

    push-to-registry:
        runs-on: [self-hosted, prod-runner]
        needs: build
        if:  ${{ (github.base_ref == 'main' && github.event.pull_request.merged == true && github.head_ref == 'release') }}
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Push production frontend image to registry
              run: |
                docker tag jubuitrago/tunefy:dev-frontend- jubuitrago/tunefy:prod-frontend-
                docker push jubuitrago/tunefy:prod-frontend-
            - name: Push production backend image to registry
              run: |
                docker tag jubuitrago/tunefy:dev-backend- jubuitrago/tunefy:prod-backend-
                docker push jubuitrago/tunefy:prod-backend-

    deploy:
        runs-on: [self-hosted, dev-runner]
        needs: push-to-registry
        if:  ${{ (github.base_ref == 'main' && github.event.pull_request.merged == true && github.head_ref == 'release') }}
        steps:
            - name: Deploy images to production environment
              run: |
                echo "deployment started"
    
    delete-feature-branch:
        runs-on: [self-hosted, dev-runner]
        needs: deploy
        if:  ${{ (github.base_ref == 'main' && github.event.pull_request.merged == true && github.head_ref == 'release') }}
        steps:
            - name: delete release and develop branch
              run: |
                echo "deleting release and develop branch"

