#cambio de prueba

name: CD Workflow - main-branch

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    runs-on: self-hosted
    if:  ${{ (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push production frontend image to registry
        run: |
          docker tag jubuitrago/tunefy:dev-frontend-latest jubuitrago/tunefy:prod-frontend-latest
          docker push jubuitrago/tunefy:prod-frontend-latest
      - name: Push production backend image to registry
        run: |
          docker tag jubuitrago/tunefy:dev-backend-latest jubuitrago/tunefy:prod-backend-latest
          docker push jubuitrago/tunefy:prod-backend-latest

  deploy:
    runs-on: self-hosted
    needs: release
    if:  ${{ (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
      - name: Send signal to deploy
        run: |
          cd /home/ubuntu
          sh start_deployment.sh














  