#cambio de prueba

name: CI Workflow - develop-branch

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && startsWith(github.ref, 'refs/heads/feature/')) }}
    steps:
    - uses: actions/checkout@v3
    - name: Stop all running containers
      run: |
        if [ "$(docker ps -q)" ]; then
          docker stop $(docker ps -q)
        fi
    - name: Delete all containers
      run: docker container prune -f
    - name: Build frontend image
      run: |
        cd frontend
        docker build -t frontend .
    - name: Build backend image
      run: |
        cd backend
        docker build -t backend .

  test:
    runs-on: self-hosted
    needs: build
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && startsWith(github.ref, 'refs/heads/feature/')) }}
    steps:
      - name: Run test
        run: echo 'here goes some test'
        
  release:
    runs-on: self-hosted
    needs: test
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && startsWith(github.ref, 'refs/heads/feature/')) }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set version
        id: set_version
        run: echo "::set-output name=VERSION::$(cat version.txt)"
      - name: Push frontend image to registry
        run: |
          docker tag frontend:latest jubuitrago/tunefy:dev-frontend-${{ steps.set_version.outputs.VERSION }}
          docker push jubuitrago/tunefy:dev-frontend-${{ steps.set_version.outputs.VERSION }}
      - name: Push backend image to registry
        run: |
          docker tag backend:latest jubuitrago/tunefy:dev-backend-${{ steps.set_version.outputs.VERSION }}
          docker push jubuitrago/tunefy:dev-backend-${{ steps.set_version.outputs.VERSION }}


