#cambio de prueba
name: CI Workflow - develop-branch

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd frontend
        docker build -t frontend_i .
        docker run -d --name tunefy-frontend frontend_i
        
