name: CI Workflow - develop-branch

on:
  pull_request:
    branches:
      - develop
    types: [opened]

jobs:
    build:
        runs-on: self-hosted
        if:  ${{ startsWith(github.event.pull_request.head.ref, 'feature/')}}
        steps:
            - uses: actions/checkout@v3
            - name: Build frontend image
              run: |
                cd frontend
                sudo docker build -t frontend .
            - name: Build backend image
              run: |
                cd backend
                sudo docker build -t backend .
    test:
        runs-on: self-hosted
        needs: build
        if:  ${{ (github.base_ref == 'develop' && startsWith(github.ref, 'refs/heads/feature/')) }}
        steps:
            - name: Test images
              run: |
                echo "running test"
                # docker run -d --name prueba frontend:latest
                # docker run -d --name prueba backend:latest
                # docker exec prueba npm test
            - name: Clean docker
              run: |
                if [ "$(sudo docker ps -q)" ]; then
                  sudo docker stop $(sudo docker ps -q)
                fi
                sudo docker system prune -af