name: CI Workflow - develop-branch

on:
    pull_request:
      branches:
        - develop
      types: [opened]

jobs:
    build:
        runs-on: [self-hosted, dev-runner]
        if:  ${{ (github.event_name == 'pull_request' && startsWith(github.ref, 'refs/heads/feature/')) }}
        steps:
            - uses: actions/checkout@v3
            - name: Build frontend image
              run: |
                cd frontend
                docker build -t frontend .
            - name: Build backend image
              run: |
                cd backend
                docker build -t backend .
    test:
        runs-on: [self-hosted, dev-runner]
        needs: build
        if:  ${{ (github.base_ref == 'develop' && startsWith(github.ref, 'refs/heads/feature/')) }}
        steps:
            - name: Test images
              run: |
                echo "running test"
                # docker run -d --name prueba frontend:latest
                # docker run -d --name prueba backend:latest
                # docker exec prueba npm test
            - name: Clean docker
              run: |
                if [ "$(docker ps -q)" ]; then
                  docker stop $(docker ps -q)
                fi
                docker system prune -af