#cambio de prueb
name: CI Workflow - develop-branch

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Stop all running containers
      run: |
        if [ "$(docker ps -q)" ]; then
          docker stop $(docker ps -q)
        fi

    - name: Delete all containers
      run: docker container prune -f

    - name: Build frontend image
      run: |
        cd frontend
        docker build -t frontend_i .

    - name: Run frontend container
      run: docker run -d --name tunefy-frontend frontend_i

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run test
        run: echo 'here goes some test'
        
