#cambio de prueba

name: CI Workflow - main-branch

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  build:
    runs-on: self-hosted
    if:  ${{ (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set version
      id: set_version
      run: echo "::set-output name=VERSION::$(cat version.txt)"
    - name: pull dev images from registry
      run: |
        docker pull jubuitrago/tunefy:dev-frontend-${{ steps.set_version.outputs.VERSION }}
        docker pull jubuitrago/tunefy:dev-backend-${{ steps.set_version.outputs.VERSION }}
    
  test:
    runs-on: self-hosted
    needs: build
    if:  ${{ (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
      - name: Test images
        run: |
          echo 'here goes some tests'
          # docker run -d --name prueba prueba:latest
          # docker exec prueba npm test

  
















  