#cambio de prueba

name: CI Workflow - main-branch

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  build:
    runs-on: self-hosted
    if:  ${{ (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: pull dev images from registry
      run: |
        docker pull jubuitrago/tunefy:dev-frontend-latest
        docker pull jubuitrago/tunefy:dev-backend-latest
    
  test:
    runs-on: self-hosted
    needs: build
    if:  ${{ (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
      - name: Test images
        run: echo 'here goes some test'
  
  release:
    runs-on: self-hosted
    needs: test
    if:  ${{ (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
      - name: Push production frontend image to registry
        run: |
          docker tag jubuitrago/tunefy:dev-frontend-latest jubuitrago/tunefy:prod-frontend-latest
          docker push jubuitrago/tunefy:prod-frontend-latest
      - name: Push production backend image to registry
        run: |
          docker tag jubuitrago/tunefy:dev-backend-latest jubuitrago/tunefy:prod-backend-latest
          docker push jubuitrago/tunefy:prod-backend-latest
















  