#cambio de prueba

name: CICD Workflow - main-branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    if:  ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref == 'develop') }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: pull dev images from registry
      run: |
        docker pull jubuitrago/tunefy:dev-frontend-latest
        docker pull jubuitrago/tunefy:dev-backend-latest

















  